### ISSUE TITLE
main dont work

### ISSUE THREAD

**Issue by epwhitey** [emppu-dev/roblox-decal-mass-uploader#14]
error:
C:\Users\User>C:\Users\User\Desktop\roblox-decal-mass-uploader-main\main.py
Traceback (most recent call last):
  File "C:\Users\User\Desktop\roblox-decal-mass-uploader-main\main.py", line 10, in <module>
    with open("config.json") as f:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

**Comment by Lazuski** [comment]
put the config.json in the same folder with main.py

**Comment by epwhitey** [comment]
i did

**Comment by emppu-dev** [comment]
Please double check that all of the project files are in the same directory.
