### ISSUE TITLE
Error getting the verification token

### ISSUE THREAD

**Issue by MilkKoun** [emppu-dev/roblox-decal-mass-uploader#4]
what da problem?

**Comment by emppu-dev** [comment]
I'm aware of the issue caused by some changes in Roblox's API and will work on a fix shortly.

**Comment by MeWasher** [comment]
so mass uploading doesn't work right now?

**Comment by MilkKoun** [comment]
still waiting for the update

**Comment by ssynical** [comment]
i would enjoy having dis fixed too

**Comment by JebacPisxd** [comment]
When will be fix?
