### ISSUE TITLE
main.py doesnt work

### ISSUE THREAD

**Issue by matile2000** [emppu-dev/roblox-decal-mass-uploader#5]
its probably an issue on my end but i cant find any other place that can get me support with this 
main.py just opens cmd for a split second and closes

**Comment by MilkKoun** [comment]
open Main.py from CMD

**Comment by emppu-dev** [comment]
> its probably an issue on my end but i cant find any other place that can get me support with this main.py just opens cmd for a split second and closes

Please run the main.py through cmd and then paste the error here.

**Comment by matile2000** [comment]
C:\Users\mati>python C:\Users\mati\OneDrive\Documents\roblox-decal-mass-uploader-main\main.py
Traceback (most recent call last):
  File "C:\Users\mati\OneDrive\Documents\roblox-decal-mass-uploader-main\main.py", line 10, in <module>
    with open("config.json") as f:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

C:\Users\mati>

**Comment by emppu-dev** [comment]
You need to download all of the needed files including the config.json

**Comment by matile2000** [comment]
i have every single file downloaded

**Comment by emppu-dev** [comment]
Make sure that the main.py and the config.json are in the same directory

**Comment by matile2000** [comment]
theyre both in the same folder
